name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide detailed information to help us reproduce and fix it.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: |
        Describe the bug in detail. Include:
        - What you were trying to do
        - Steps to reproduce the behavior
        - What you expected to happen
        - What actually happened (include error messages, logs, screenshots)
      placeholder: |
        When I run command `...`, I expect X to happen, but instead Y happens.

        Steps to reproduce:
        1. Run command '...'
        2. Execute script '...'
        3. See error

        Expected: The function should return...

        Actual: Error: ...
        Traceback: ...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: System Information
      description: Run `scripts/get_system_info.sh` and paste the output here (helps with debugging)
      placeholder: Paste the output of scripts/get_system_info.sh here...
      render: text
