name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide detailed information about what you'd like to see.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: |
        Describe the feature you'd like to see. Include:
        - What problem this solves or use case it addresses
        - How you'd like this feature to work
        - Alternative solutions you've considered
        - Examples of how this would be used (code snippets, CLI commands, etc.)
      placeholder: |
        **Problem/Use Case:**
        I'm frustrated when... / I need to... / It would be helpful if...

        **Proposed Solution:**
        I would like to see... / The system should...

        **Alternatives Considered:**
        - Alternative A...
        - Alternative B...

        **Example Usage:**
        ```python
        # Example code showing how this feature would be used
        from ml_odyssey import new_feature
        result = new_feature.do_something()
        ```
    validations:
      required: true
