name: 📄 Paper Implementation Request
description: Request reproduction of a research paper
title: "[Paper] "
labels: ["paper", "research", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Request implementation of a research paper! This will create a full paper reproduction workflow
        following our 4-level hierarchical planning structure.

  - type: textarea
    id: description
    attributes:
      label: Paper Information
      description: |
        Provide complete information about the paper. Include:
        - Title, authors, year, venue, URL
        - Paper abstract or brief description
        - Category (CV, NLP, RL, etc.)
        - Why this paper should be implemented
        - Required datasets, dependencies, and resources
        - Available reference implementations or pretrained models
      placeholder: |
        **Title**: Gradient-Based Learning Applied to Document Recognition

        **Authors**: LeCun, Y., Bottou, L., Bengio, Y., Haffner, P.

        **Year**: 1998

        **Venue**: Proceedings of the IEEE

        **URL**: https://ieeexplore.ieee.org/document/726791

        **Category**: Computer Vision

        **Abstract/Description**: This paper presents...

        **Why implement this paper:**
        This paper is important because...
        It would enable...
        It's a foundational work in...

        **Datasets Required:**
        - MNIST (handwritten digits)
        - CIFAR-10 (image classification)

        **Dependencies:**
        - Large GPU memory (16GB+)
        - External libraries

        **Available Resources:**
        - Official code is available at...
        - Pretrained models available
        - Community reproductions at...
    validations:
      required: true
