name: 📄 Paper Implementation Request
description: Request reproduction of a research paper
title: "[Paper] "
labels: ["paper", "research", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Request implementation of a research paper! This will create a full paper reproduction workflow
        following our 4-level hierarchical planning structure.

  - type: textarea
    id: paper-description
    attributes:
      label: Paper Information
      description: Provide complete information about the paper
      placeholder: |
        **Title**: Gradient-Based Learning Applied to Document Recognition

        **Authors**: LeCun, Y., Bottou, L., Bengio, Y., Haffner, P.

        **Year**: 1998

        **Venue**: Proceedings of the IEEE

        **URL**: https://ieeexplore.ieee.org/document/726791

        **Abstract**: This paper presents...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of paper is this?
      options:
        - Computer Vision
        - Natural Language Processing
        - Reinforcement Learning
        - Generative Models
        - Optimization
        - Architecture
        - Other
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why should we implement this paper? What datasets, dependencies, or resources are needed?
      placeholder: |
        **Why implement this paper:**
        This paper is important because...
        It would enable...
        It's a foundational work in...

        **Datasets Required:**
        - MNIST (handwritten digits)
        - CIFAR-10 (image classification)

        **Dependencies:**
        - Large GPU memory (16GB+)
        - External libraries

        **Available Resources:**
        - Official code is available at...
        - Pretrained models available
        - Community reproductions at...
    validations:
      required: true
