name: 📚 Documentation Improvement
description: Suggest improvements to documentation
title: "[Docs] "
labels: ["documentation", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation! Clear, comprehensive docs are critical for the project.

  - type: textarea
    id: description
    attributes:
      label: Documentation Improvement
      description: |
        Describe what documentation needs improvement. Include:
        - Type of documentation (README, API docs, tutorial, code comments, etc.)
        - Location (file path, section, lines)
        - What's unclear, incorrect, or missing
        - How it should be improved
        - Who would benefit from this improvement
        - Examples or references to good documentation
      placeholder: |
        **Type**: README / Getting Started

        **Location**:
        File: /path/to/file.md
        Section: "Getting Started"
        Lines: 50-75

        **Problem**:
        The current documentation...
        This section is confusing because...
        Missing information about...

        **Proposed Improvement**:
        Add section explaining...
        Clarify that...
        Include example showing...

        **Target Audience**:
        - New contributors
        - Paper implementers
        - Agent system users

        **Examples or References**:
        Good example from project X...
        Could include code like:
        ```python
        # Example code
        ```
    validations:
      required: true
