name: 🔧 Infrastructure / Tooling
description: Infrastructure, tooling, or developer experience improvements
title: "[Infra] "
labels: ["infrastructure", "tooling", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Suggest improvements to project infrastructure, tooling, or developer experience.

  - type: textarea
    id: description
    attributes:
      label: Infrastructure Improvement
      description: |
        Describe the infrastructure or tooling improvement. Include:
        - What problem this solves or pain point it addresses
        - Proposed solution
        - Implementation details (tools, technologies, key steps)
        - Alternatives considered
        - Risks, trade-offs, and considerations
      placeholder: |
        **Problem:**
        Currently, developers need to...
        The build process is slow because...
        Testing is difficult because...

        **Proposed Solution:**
        Add a new script that...
        Update the CI pipeline to...
        Implement automation for...

        **Implementation Details:**
        Tools/technologies needed:
        - Tool A for...
        - Library B for...

        Key steps:
        1. Configure...
        2. Implement...
        3. Test...

        **Alternatives Considered:**
        - Option A: ... (rejected because...)
        - Option B: ... (could work but...)

        **Risks/Considerations:**
        - May increase build time
        - Requires additional dependencies
        - Breaking change for existing workflows
    validations:
      required: true
