name: ❓ Question / Support
description: Ask a question about the project
title: "[Question] "
labels: ["question", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!

        **Note**: For longer discussions, consider using [GitHub Discussions](https://github.com/mvillmow/ml-odyssey/discussions).

  - type: textarea
    id: question
    attributes:
      label: Question
      description: |
        What would you like to know? Include:
        - Your question
        - Context about what you're trying to do
        - What you've already tried or looked at
        - System information (if relevant, run `python3 scripts/get_system_info.py`)
      placeholder: |
        **Question:**
        How do I... / Why does... / What is...

        **Context:**
        I'm trying to...
        I've looked at...
        I expected... but...

        **What I've Tried:**
        - Read the documentation at...
        - Tried approach X...
        - Searched for...

        **System Information (if relevant):**
        Paste output of `python3 scripts/get_system_info.py` here
    validations:
      required: true
